apiVersion: apps/v1
kind: Deployment
metadata:
  name: ajcn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ajcn
  template:
    metadata:
      labels:
        app: ajcn
    spec:
      containers:
        - name: nginx
          image: registry.digitalocean.com/ajcn/site:${TAG}
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ajservice
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: ajcn

