apiVersion: apps/v1
kind: Deployment
metadata:
  name: site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: site
  template:
    metadata:
      labels:
        app: site
    spec:
      containers:
        - name: site
          image: ajcn06/personal-nginx-01
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: site-service
spec:
  type: LoadBalancer
  ports:
      port: 80
      targetPort: 80
  selector:
    app: site

