on:
  push:
    branches:
      - main
    paths:
      - 'config/**'
      - 'site/**'
      - 'Dockerfile'
      - '.github/workflows/**'

jobs:
  push_docker:
    name: Push docker image  
    runs-on: ubuntu-latest
    steps:

    - name: Checkout main
      uses: actions/checkout@v2

    - name: Build & Push to Docker Hub
      uses: zenato/docker-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ajcn06/personal-nginx-01
        tag: latest

  k8s_deploy:
    name: K8s Deploy  
    needs: push_docker
    runs-on: ubuntu-latest
    steps:

    # - name: Checkout main
    #   uses: actions/checkout@v2

    # - name: Update SHA
    #   run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta

    # - name: Build container image
    #   run: docker build -t registry.digitalocean.com/ajcn/site:$(echo $GITHUB_SHA | head -c7) .

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    # - name: Log in to DigitalOcean Container Registry with short-lived credentials
    #   run: doctl registry login --expiry-seconds 600

    # - name: Push image to DigitalOcean Container Registry
    #   run: docker push registry.digitalocean.com/ajcn/site:$(echo $GITHUB_SHA | head -c7)

    # - name: Update deployment file
    #   run: $GITHUB_WORKSPACE/config/deployment.yml

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 nearlinx-research

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl apply -f $GITHUB_WORKSPACE/config/deployment.yml

    - name: Verify deployment
      run: kubectl rollout status deployment/site